---
name: diyHue
version: dev
slug: diyhue
description: Philips Hue Bridge Emulator
url: https://github.com/r0bb10/ha-addons/diyhue
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
panel_icon: mdi:home-lightbulb
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
auth_api: true
hassio_api: true
uart: true
map:
  - config:rw
  - share:rw
ports:
  80/tcp: 80
  443/tcp: 443
  1900/udp: 1901
  1982/udp: 1982
  2100/udp: 2100
ports_description:
  80/tcp: Hue API
  443/tcp: Hue API SSL
  1900/udp: ssdp Discover
  1982/udp: Yeelight detection
  2100/udp: Hue Entertainment
options:
  config_path: /config/diyhue
  mac: "XX:XX:XX:XX:XX:XX"
  debug: false
  deconz_ip: ""
  no_serve_https: false
schema:
  config_path: str
  mac: str
  debug: bool
  deconz_ip: str
  no_serve_https: bool
